version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.netty:netty-all
    versions:
    - 4.1.60.Final
    - 4.1.61.Final
    - 4.1.62.Final
  - dependency-name: org.jetbrains.kotlin:kotlin-reflect
    versions:
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-test-junit
    versions:
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.0
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-jdk8
    versions:
    - 1.3.9
    - 1.4.2-native-mt
  - dependency-name: io.codearte.nexus-staging
    versions:
    - 0.22.0
  - dependency-name: org.junit.platform:junit-platform-runner
    versions:
    - 1.7.0-RC1
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0-RC1
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0-RC1
